version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: arlab-postgres
    restart: always
    environment:
      POSTGRES_USER: arlab_user
      POSTGRES_PASSWORD: yoursecurepassword # Cambia esto por una contrase√±a segura
      POSTGRES_DB: arlab_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: